### ISSUE TITLE
Artist page/widget not loading

### ISSUE THREAD

**Issue by gansheer** [aome510/spotify-player#330] opened 2024-01-05 16:32 UTC
**Describe the bug**
When trying to access any artist, the view stays blocked on "loading..."

**To Reproduce**
Select an artist.

**Expected behavior**
To display the details of the artist :smile: .

**Log and backtrace**
```
...
2024-01-05T16:19:24.483948Z ERROR client_request{request=GetContext(Artist(ArtistId("1dfeR4HaWDbWqFHLkxsg1d")))}: spotify_player::client::handlers: Failed to handle client request: json parse error: invalid type: floating point `49022220`, expected u32 at line 1 column 129: invalid type: floating point `49022220`, expected u32 at line 1 column 129
2024-01-05T16:19:25.429942Z  INFO client_request{request=GetContext(Artist(ArtistId("1dfeR4HaWDbWqFHLkxsg1d")))}: spotify_player::client: Get artist context: spotify:artist:1dfeR4HaWDbWqFHLkxsg1d
2024-01-05T16:19:25.481751Z ERROR client_request{request=GetContext(Artist(ArtistId("1dfeR4HaWDbWqFHLkxsg1d")))}: spotify_player::client::handlers: Failed to handle client request: json parse error: invalid type: floating point `49022220`, expected u32 at line 1 column 129: invalid type: floating point `49022220`, expected u32 at line 1 column 129
...
```

**Screenshots**
![Capture d’écran du 2024-01-05 17-19-02](https://github.com/aome510/spotify-player/assets/6067789/1e05fe62-142d-4c4a-8d9c-dff57cdfc85b)

**Environment**

- OS: Linux
- Application version: 0.16.3 (github release spotify_player-x86_64-unknown-linux-gnu-0.16.3.tar.gz)
- Application features: N/A

**Additional context**
Started suddenly, I tried clearing the cache to no avail.
The command line give me the same result:
```
$ spotify-player get item artist --id 1dfeR4HaWDbWqFHLkxsg1d
Bad request: json parse error: invalid type: floating point `49022220`, expected u32 at line 1 column 129: invalid type: floating point `49022220`, expected u32 at line 1 column 129
```

**Comment by aome510** [comment] 2024-01-06 11:49
Look like the error happens because of a recent change from Spotify that changes the type of a field from integer to float. I submitted a bug issue to the third-party library that handles Spotify APIs: https://github.com/ramsayleung/rspotify/issues/452

**Comment by SkepticMystic** [comment] 2024-01-10 09:35
+1
Another Spotify player I use is having the same issue 😅 
Bit of context, if it helps:
- https://github.com/KRTirtho/spotube/issues/1018
- https://github.com/rinukkusu/spotify-dart/issues/193

**Comment by LucasFA** [comment] 2024-02-03 13:23
Of note: a workaround has been merged to rspotify: https://github.com/ramsayleung/rspotify/pull/457

**Comment by aome510** [comment] 2024-03-02 23:01
Encountered another error in https://github.com/aome510/spotify-player/issues/383#issuecomment-1972452044 but with [`get-several-tracks ` API](https://developer.spotify.com/documentation/web-api/reference/get-several-tracks). As it may take `rspotify` quite a while to implement/release patches, I'll implement a workaround from `spotify_player` side.

**Closed** 2024-03-03 17:18 UTC
Labels: bug

**Comment by aome510** [comment] 2024-03-03 17:19
Should be fixed by https://github.com/aome510/spotify-player/pull/386. Can anyone try running from the latest `master` to see if the issue is fixed now?
