### ISSUE TITLE
spotify_player asking for a username and password

### ISSUE THREAD

**Issue by mariano-daniel** [aome510/spotify-player#201] opened 2023-05-22 04:59 UTC
I looked up the main page and documentation page and nowhere this is mentioned.

I tried the API client_id, my email username, the username that shows on my profile, none of them work.

What am I supposed to enter when it's asking for my username? 🤷🏻‍♂️

```
spotify_player
No cached credentials found, please authenticate the application first.
Username: xxxxx@icloud.com
Password for xxxxx@icloud.com: 
Failed to authenticate, 2 tries left
Username (default: xxxxxx@icloud.com): al3dtskdslj3b35s40
Password for al3dtskdslj3b35s40: 
Failed to authenticate, 1 tries left
Username (default: al3dtskdslj3b35s40): 
```

**Comment by aome510** [comment] 2023-05-22 18:29
I'm not sure if you have the same thing but in my case, Spotify username should be able to find on the [Account Overview website](https://www.spotify.com/account/overview/). Here is mine for reference (`username` is the first one and `email` is the second one):

<img width="861" alt="Screenshot 2023-05-22 at 2 27 38 PM" src="https://github.com/aome510/spotify-player/assets/40011582/a18ae161-a278-4cd2-ad8c-b7fec68f1ce1">

**Comment by mariano-daniel** [comment] 2023-05-22 19:59
Hello Thang Pham! Yep, that’s the one I’ve used and it did not work. Did it
work for you?

Regards ,

**Comment by aome510** [comment] 2023-05-22 20:05
> Hello Thang Pham! Yep, that’s the one I’ve used and it did not work. Did it
work for you?

Just tried and it still works for me. Can you also provide the logs in ~/.cache/spotify_player` if any?

**Comment by mariano-daniel** [comment] 2023-05-23 00:55
[spotify-player-23-05-22-02-05.log](https://github.com/aome510/spotify-player/files/11538092/spotify-player-23-05-22-02-05.log)


Hello @aome510 ! Logs attached. unfortunately they don't seem to be very verbose, just say bad credentials. But i'm entering the same info when I'm login into my spotify profile, but using the username you mentioned on your screenshot (but for me, of course)

**Comment by aome510** [comment] 2023-05-23 01:16
hmmm, that's really weird. At this point, I actually don't know the cause. Can you double check if the same combination of `username` and `password` works in the official Spotify website?

**Comment by mariano-daniel** [comment] 2023-05-23 03:45
> hmmm, that's really weird. At this point, I actually don't know the cause. Can you double check if the same combination of `username` and `password` works in the official Spotify website?

Yep, it works when I login to the site, not when I try the program. I can email you a video with tests.

Thanks!

**Comment by adworacz** [comment] 2023-05-24 16:58
I'm running into this as well - I created a new client ID in my spotify account (although I have no idea what to set the redirect URL to, and there's nothing mentioned in the `config.md` documentation about what to use).

I've tried twice now to enter my credentials, and I'm getting timeouts of some kind:

```
2023-05-24T16:55:26.147375Z  INFO spotify_player::auth: Creating a new session with new authentication credentials
2023-05-24T16:57:49.906749Z  WARN spotify_player::auth: Failed to authenticate: Cannot create session: Connection timed out (os error 110)
```

**Comment by aome510** [comment] 2023-05-24 17:37
> Yep, it works when I login to the site, not when I try the program. I can email you a video with tests.

Can u email me an email if possible?

>  I created a new client ID in my spotify account (although I have no idea what to set the redirect URL to, and there's nothing mentioned in the config.md documentation about what to use), so I just used http://localhost:8080/.

Did u put `client_id = "http://localhost:8080/"`? You don't need a redirect URL for `spotify_player` unlike `spotify-tui`. `spotify-player` relies on username/password to authenticate. `client_id` is only needed if you want to use https://github.com/aome510/spotify-player#spotify-connect.

> It's recommended to specify [your own Client ID](https://developer.spotify.com/documentation/web-api/concepts/apps) to avoid possible rate limits and to allow a full [Spotify connect](https://www.spotify.com/us/connect/) support.

From `config.md` document, it's not required to specify your own client ID though.

**Comment by adworacz** [comment] 2023-05-25 00:44
Spotify requires that you specify a redirect URL when creating the client ID, otherwise it errors:

![2023-05-24_17:41:39_maim](https://github.com/aome510/spotify-player/assets/561689/44fdd160-7720-451e-b5e5-93595f63add5)

> Did u put client_id = "http://localhost:8080/"? 

No I didn't. I put the client ID generated via the Spotify Developer website. And I only tried to generate a client ID after the first attempt at using username/password failed.

The same timeout occurs if I comment out the `client_id` entry in `app.toml`.

**Comment by aome510** [comment] 2023-05-25 15:40
@adworacz thanks for the clarification. Can you try running `RUST_LOG=debug spotify_player` and send me a corresponding log?

Related issue: https://github.com/librespot-org/librespot/issues/1010. Look like this happens because `librespot` couldn't connect to a specific AP.

**Comment by adworacz** [comment] 2023-05-25 16:29
I'd wager you're correct on that linked issue. 

Here's the pertinent logs I see when using `RUST_LOG=debug`

```
2023-05-25T16:25:31.793573Z  INFO spotify_player::auth: Creating a new session with new authentication credentials
2023-05-25T16:25:46.650291Z DEBUG hyper::client::connect::dns: resolving host="apresolve.spotify.com"
2023-05-25T16:25:46.691555Z DEBUG hyper::client::connect::http: connecting to 34.98.74.57:80
2023-05-25T16:25:46.736232Z DEBUG hyper::client::connect::http: connected to 34.98.74.57:80
2023-05-25T16:25:46.736799Z DEBUG hyper::proto::h1::io: flushed 47 bytes
2023-05-25T16:25:46.829042Z DEBUG hyper::proto::h1::io: parsed 5 headers
2023-05-25T16:25:46.829083Z DEBUG hyper::proto::h1::conn: incoming body is content-length (169 bytes)
2023-05-25T16:25:46.829113Z DEBUG hyper::proto::h1::conn: incoming body completed
2023-05-25T16:25:46.829175Z DEBUG hyper::client::pool: pooling idle connection for ("http", apresolve.spotify.com:80)
2023-05-25T16:25:46.829266Z  WARN librespot_core::apresolve: Ignoring blacklisted access point ap-gue1.spotify.com:4070
2023-05-25T16:25:46.829273Z  WARN librespot_core::apresolve: Ignoring blacklisted access point ap-gew4.spotify.com:80
2023-05-25T16:25:46.829280Z  INFO librespot_core::session: Connecting to AP "ap-guc3.spotify.com:4070"
2023-05-25T16:27:57.722605Z  WARN spotify_player::auth: Failed to authenticate: Cannot create session: Connection timed out (os error 110)
```

**Comment by adworacz** [comment] 2023-05-25 16:33
Ahhhh now this is interesting - it seems to be related to my work VPN. 

If I'm off VPN, I can login just fine and start playing music. If I'm on VPN, I can't start spotify-player at all, even after having successfully authenticated while off VPN.

This is interesting, since I don't have these issues with `spotify-tui` + `spotifyd` while on VPN.

**Comment by mariano-daniel** [comment] 2023-05-25 22:27
> > Yep, it works when I login to the site, not when I try the program. I can email you a video with tests.
> 
> Can u email me an email if possible?

I didn't quite get this request. What should I put in the email?

**Comment by aome510** [comment] 2023-05-26 02:06
> I didn't quite get this request. What should I put in the email?

I thought you're going to send an email with the video. FYI, my email: phamducthang1234@gmail.com

**Comment by mariano-daniel** [comment] 2023-05-28 01:17
> > I didn't quite get this request. What should I put in the email?
> 
> I thought you're going to send an email with the video. FYI, my email: [phamducthang1234@gmail.com](mailto:phamducthang1234@gmail.com)

Email sent! Thank you.

**Comment by aome510** [comment] 2023-05-28 01:32
@mariano-daniel thanks for the video. Look like the login is failed because you're not in premium account. A premium account is **required** to use `spotify_player`.

**Comment by mariano-daniel** [comment] 2023-05-28 01:34
> @mariano-daniel thanks for the video. Look like the login is failed because you're not in premium account. A premium account is **required** to use `spotify_player`.

But why would it throw bad credentials though? Shouldn't at least me log me in and then throw an error?

**Comment by aome510** [comment] 2023-05-28 01:40
> But why would it throw bad credentials though? 

Exactly =)). It used to throw a better error: https://github.com/aome510/spotify-player/issues/29#issuecomment-966393666

It seems to change because I updated the printing mechanism for error from `debug` to `normal`. 

The reason is that the third-party library that `spotify_player` relies mostly for handling Spotify stuff doesn't support it: https://github.com/librespot-org/librespot/issues/862

I'll close this issue for now. Feel free to re-open it if you encounter similar issues.

**Closed by aome510** 2023-05-28 01:40 UTC
Labels: bug

**Comment by ManiArasteh** [comment] 2024-08-19 11:28
@yashrajbains Read [README.md](https://github.com/aome510/spotify-player?tab=readme-ov-file#important-notice)

**Comment by apprehensions** [comment] 2024-09-23 12:24
Why isn't this clarified or documented in the README going over how exactly to use it? Would be nice for it to be painless in spotify-player, whether it be done automatically, written out, or a warning to be shipped to new logins.

**Comment by ManiArasteh** [comment] 2024-09-23 12:27
No needed anymore! Just wait for a new version of spotify_player

**Comment by apprehensions** [comment] 2024-09-23 12:28
You mean a new update, not version. I am on the latest git commit of spotify_player and i still have to do this.

**Comment by ManiArasteh** [comment] 2024-09-23 12:30
Yep... I mean, no! I mean new release

**Comment by apprehensions** [comment] 2024-09-23 15:48
```
$ ~/src/librespot-auth/target/debug/librespot-auth --name "kosoku"
Open Spotify and select output device: kosoku
Credentials saved: credentials.json
$ ~/src/spotify-player/target/debug/spotify_player
Error: Failed to initialize the Spotify data

Caused by:
    Token is not valid
$ pwd
/home/sewn/.cache/spotify-player
```
still no docs on how to use this side by side with spotify-player

**Comment by snikoletopoulos** [comment] 2024-10-26 12:29
I still have the same issue on 2 laptops running mac and linux.
I have the correct `client_id` and even tried the `ap_port = 443` put still its not working

here are the logs:

```
2024-10-26T12:25:32.515688Z DEBUG hyper::proto::h1::io: flushed 47 bytes
2024-10-26T12:25:32.537093Z DEBUG hyper::proto::h1::io: parsed 7 headers
2024-10-26T12:25:32.537199Z DEBUG hyper::proto::h1::conn: incoming body is content-length (169 bytes)
2024-10-26T12:25:32.537284Z DEBUG hyper::proto::h1::conn: incoming body completed
2024-10-26T12:25:32.537311Z DEBUG hyper::client::pool: pooling idle connection for ("http", apresolve.spotify.com:80)
2024-10-26T12:25:32.537430Z  WARN librespot_core::apresolve: Ignoring blacklisted access point ap-gew4.spotify.com:4070    
2024-10-26T12:25:32.537444Z  WARN librespot_core::apresolve: Ignoring blacklisted access point ap-gew4.spotify.com:443    
2024-10-26T12:25:32.537454Z  WARN librespot_core::apresolve: Ignoring blacklisted access point ap-gew4.spotify.com:80    
2024-10-26T12:25:32.537466Z  WARN librespot_core::apresolve: Ignoring blacklisted access point ap-gue1.spotify.com:443    
2024-10-26T12:25:32.537479Z  WARN librespot_core::apresolve: Failed to resolve Access Point: Unable to resolve any viable access points.    
2024-10-26T12:25:32.537487Z  WARN librespot_core::apresolve: Using fallback "ap.spotify.com:443"    
2024-10-26T12:25:32.537495Z  INFO librespot_core::session: Connecting to AP "ap.spotify.com:443"    
2024-10-26T12:25:32.732270Z  WARN spotify_player::auth: Failed to authenticate: Login failed with reason: Bad credentials
```

**Comment by apprehensions** [comment] 2024-10-26 12:31
https://github.com/aome510/spotify-player?tab=readme-ov-file#important-notice
