### ISSUE TITLE
How do I run this on Windows i'm confused.

### ISSUE THREAD

**Issue by BubbyWoodz** [aome510/spotify-player#324] opened 2023-12-24 03:30 UTC
I am confused how to run this on Windows. I have Cargo fully installed and ready to go and when I download the exe and try to run it ,it just crashes.

**Comment by BubbyWoodz** [comment] 2023-12-24 06:57
Edit 1: I installed it with scoop and it still crashes so idk

**Comment by aome510** [comment] 2023-12-24 18:31
Can you provide more details, otherwise I cannot identify the cause? For example, what is the crash message? Are there any logs/backtraces in the cache folder?

**Comment by BubbyWoodz** [comment] 2023-12-24 23:43
I could not find the logs but when I try to run the Spotify_Player.exe in the cd I get this error: "Error: Cannot create a file when that file already exists. (os error 183)"

**Comment by aome510** [comment] 2023-12-25 15:41
> I could not find the logs but when I try to run the Spotify_Player.exe in the CMD I get this error: "Error: Cannot create a file when that file already exists. (os error 183)" There is no crash message it doesn't even open it tries to and then exits.

Where did you find the logs? You can check the application cache folder location by looking into `spotify_player -h`:

```
spotify_player -h

...
Options:
  -t, --theme <THEME>           Application theme
  -c, --config-folder <FOLDER>  Path to the application's config folder [default: /Users/aome510/.config/spotify-player]
  -C, --cache-folder <FOLDER>   Path to the application's cache folder [default: /Users/aome510/.cache/spotify-player]
  -h, --help                    Print help
  -V, --version                 Print version
```

**Comment by aome510** [comment] 2024-01-06 13:57
@BubbyWoodz any updates? Otherwise, I’ll close this issue

**Closed** 2024-01-12 09:23 UTC
